[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "soft-clustering"
authors = [{name = "-", email = "-"}]
dynamic = ["version", "description"]
dependencies = [
  "numpy",
  "scipy",
  "torch"
]

