#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 The SCPP developers. See LICENSE for details.

"""Generate optimization/inventory.md from measured data.

Joins the static audit (loop structure, numerical anti-patterns) with the
baseline runtime survey, so every column is something observed rather than
asserted. Regenerate after re-running the survey.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(HERE))

import soft_clustering as sc  # noqa: E402

# Which module implements which exported estimator.
MODULE_OF = {name: path.lstrip(".") for name, path in sc._ESTIMATORS.items()}

FAMILY = {
    "FCM": "fuzzy",
    "PCM": "possibilistic",
    "PFCM": "possibilistic",
    "GK": "fuzzy",
    "ECM": "evidential",
    "KFCM": "kernel",
    "SKFCM": "kernel",
    "KFCCL": "kernel",
    "CAFCM": "fuzzy",
    "CAFHFCM": "fuzzy",
    "ENTROPYFCM": "fuzzy",
    "AFCM": "fuzzy",
    "AFCMSimple": "fuzzy",
    "AFCMAdaptive": "fuzzy",
    "FCC": "fuzzy",
    "RPFKM": "fuzzy",
    "SFCMEP": "semi-supervised",
    "FeMIFuzzy": "federated",
    "RoughKMeans": "rough",
    "SCM": "subtractive",
    "SoftDBSCANGM": "density",
    "SoftKSC": "spectral",
    "GMM": "mixture",
    "BGMM": "mixture",
    "MBMM": "mixture",
    "RDFKC": "deep",
    "BIGCLAM": "graph",
    "BayesianNMF": "graph",
    "MMSB": "graph",
    "NOCD": "deep",
    "DMoN": "deep",
    "CDCGS": "deep",
    "LDA": "document",
    "PLSI": "document",
    "SISC": "document",
    "KMART": "document",
    "WBSC": "document",
    "SCSPA": "ensemble",
    "SHBGF": "ensemble",
    "SMCLA": "ensemble",
}

# Conclusions drawn from the profiling runs. Only algorithms actually profiled
# carry a measured bottleneck; the rest are marked as not yet profiled so the
# distinction stays visible.
PROFILED = {
    "SoftDBSCANGM": (
        "N*k^2 scalar `scipy...mahalanobis` calls per iteration (1,036,800 at n=80)",
        "low (scalars); optimization trades memory for time",
        "**done — 889-4507x**",
    ),
    "MBMM": (
        "`scipy.stats.beta.logpdf` called K*D times per E-step and per log-likelihood",
        "low",
        "**done — 6.3-16.9x**",
    ),
    "SCSPA": (
        "~1 s floor independent of n; sklearn KMeans `n_init` + BLAS threads",
        "69.9 MB traced peak",
        "high (untouched)",
    ),
    "SHBGF": (
        "~1 s floor independent of n; sklearn KMeans `n_init` + BLAS threads",
        "69.9 MB traced peak",
        "high (untouched)",
    ),
    "SMCLA": (
        "~1 s floor independent of n; sklearn KMeans `n_init` + BLAS threads",
        "69.9 MB traced peak",
        "high (untouched)",
    ),
    "KFCCL": (
        "41,346 `np.sum` calls — per-element Python reduction",
        "unchanged (both builds hold the (N,N) kernel)",
        "**done — 26.5-152.0x**",
    ),
    "KMART": (
        "28,634 `np.sum` calls in `_fuzzy_and`",
        "unchanged",
        "**done — 9.8-71.2x**",
    ),
    "KFCM": (
        "`typeguard` check_type_internal 22.5 ms + isinstance 17.5 ms of 175 ms, "
        "riding on N*k scalar kernel calls per iteration",
        "low (0.26 -> 0.86 MB at n=1600)",
        "**done — 81.9-545.5x**",
    ),
    "AFCM": (
        "`scipy.linalg.eigh` 126.9 ms of 440 ms (dense eigendecomposition)",
        "low",
        "medium (untouched)",
    ),
    "SISC": (
        "`_tanimoto_similarity` over Python sets, 10,624 calls",
        "low",
        "medium (untouched)",
    ),
}


def main() -> int:
    static = json.loads(
        subprocess.run(
            [sys.executable, str(HERE / "audit_static.py"), "--json"],
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout
    )
    by_module = {s["module"].removesuffix(".py"): s for s in static}

    survey = {}
    csv_path = HERE / "benchmarks" / "results.csv"
    if csv_path.exists():
        for row in csv.DictReader(csv_path.open()):
            if row["implementation"] == "survey" and row["status"] == "ok":
                survey[row["algorithm"]] = float(row["fit_time_ms"])

    lines = [
        "# Algorithm inventory",
        "",
        "Generated by `python optimization/make_inventory.py`. Every column is",
        "measured: loop structure and numerical call sites come from the AST audit",
        "(`audit_static.py`), baseline timings from the survey sweep",
        "(`optimization/benchmarks/results.csv`, `implementation == survey`,",
        "n = 200, d = 8, k = 3, single fit).",
        "",
        "`Baseline` is blank where the estimator is not in the harness registry —",
        "it takes an input shape the shared registry does not build (see",
        "`optimization/harness.py`). Those are audited statically but not timed.",
        "",
        "**Implementation provenance.** Every algorithm in SCPP is a direct,",
        "SCPP-specific implementation of its published method written against",
        "NumPy/SciPy. None wraps a third-party estimator, and none is a vendored",
        "copy of reference code; `scikit-learn` is used only for supporting",
        "primitives (DBSCAN, KMeans, eigen-solvers) inside some methods.",
        "",
        "| Algorithm | Family | Module | Code LOC | Loops (max depth) | Numerical flags | Baseline (ms) | Measured bottleneck | Memory | Optimization status |",
        "| --- | --- | --- | ---: | ---: | --- | ---: | --- | --- | --- |",
    ]

    for name in sorted(MODULE_OF):
        mod = MODULE_OF[name]
        s = by_module.get(mod, {})
        flags = (
            ", ".join(f"{k}x{v}" for k, v in sorted(s.get("patterns", {}).items()))
            or "—"
        )
        base = f"{survey[name]:,.1f}" if name in survey else "—"
        bott, mem, status = PROFILED.get(
            name, ("not yet profiled", "not yet profiled", "unknown — not yet profiled")
        )
        lines.append(
            f"| `{name}` | {FAMILY.get(name,'')} | `{mod}.py` | {s.get('code_loc','')} | "
            f"{s.get('n_loops','')} ({s.get('max_loop_depth','')}) | {flags} | {base} | "
            f"{bott} | {mem} | {status} |"
        )

    lines += [
        "",
        "## Coverage of this study",
        "",
        f"- Algorithms exported by SCPP: **{len(MODULE_OF)}**",
        f"- Statically audited: **{len(by_module)}**",
        f"- Baseline-timed in the survey: **{len(survey)}**",
        f"- Profiled in detail: **{len(PROFILED)}**",
        "- Optimized, verified and benchmarked end to end: "
        f"**{sum(1 for v in PROFILED.values() if v[2].startswith('**done'))}**",
        "",
        "The gap between *profiled* and *optimized* is deliberate and is discussed",
        "in the report under 'Algorithms not optimized' and 'Limitations'.",
        "",
        "## Notes on untimed algorithms",
        "",
        "`AFCMAdaptive`, `SKFCM`, `RDFKC` (image inputs), `BGMM` (two aligned",
        "views), `SoftKSC` (labelled and unlabelled parts), `FeMIFuzzy` (a list of",
        "client matrices), `LDA` (returns factors rather than a partition) and the",
        "four PyTorch estimators `CDCGS`, `DMoN`, `MMSB`, `NOCD` are excluded from",
        "the shared harness for the same reasons `tests/test_protocol.py` excludes",
        "them. `BIGCLAM` requires `n_nodes` at construction and is registered but",
        "was not timed in this survey.",
    ]

    (HERE / "inventory.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {HERE/'inventory.md'} ({len(MODULE_OF)} algorithms)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
